[package]
name = "airpods-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "airpods-cli"
path = "src/main.rs"

[dependencies]
zbus.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
clap = { version = "4", features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
