[package]
name = "airpods-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
aap.workspace = true
tokio = { workspace = true, features = ["rt", "macros", "sync", "time", "process", "signal", "io-util"] }
bluer = { version = "0.17", features = ["l2cap", "bluetoothd"] }
zbus.workspace = true
serde.workspace = true
toml = "1"
tracing.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std", "ansi"] }
thiserror.workspace = true
anyhow.workspace = true
futures = "0.3"
serde_json.workspace = true
libc = "0.2"
toml_edit = "0.25"
